[package]
name = "superstack"
version = "0.1.0"
edition = "2021"

[dependencies]
mini-telnet = "0.1.8"
tokio = { version = "1.23.0", features = ["full"] }
anyhow = "1.0.68"
dotenv = "0.15.0"
thiserror = "1.0.38"